### ISSUE TITLE
TypeScript error with enhancers

### ISSUE THREAD

**Issue by NDKhanh96** [matt-oakes/redux-devtools-expo-dev-plugin#14] opened 2024-10-24 13:25 UTC
I am following the doc but getting this error
![Screenshot 2024-10-24 at 20 13 39](https://github.com/user-attachments/assets/5f5c4bbc-e0d3-4a03-9ebf-ec0023bb4056)
this is prettier version
![Screenshot 2024-10-24 at 20 12 54](https://github.com/user-attachments/assets/a0283c27-4ad1-444e-8962-435fb89a7fd0)
and this is my package.json
![Screenshot 2024-10-24 at 20 22 04](https://github.com/user-attachments/assets/2436ec3b-17ff-4c14-b3ad-6bf70123eb2a)
Is there something wrong in my code or am I just missing something

**Comment by matt-oakes** [comment] 2024-11-09 15:07
Duplicate of #12

**Closed as not planned by matt-oakes** 2024-11-09 15:07 UTC
