### ISSUE TITLE
Error: Unauthorized request from http://x.x.x.x:yyyy

### ISSUE THREAD

**Issue by theogravity** [matt-oakes/redux-devtools-expo-dev-plugin#3] opened 2024-06-04 01:14 UTC
Just reporting this in case you haven't seen this on your own machine:

```
Error: Unauthorized request from http://172.16.1.16:8081. This may happen because of a conflicting browser extension to intercept HTTP requests. Please try again without browser extensions or using incognito mode.
    at /Users/theo/projects/monarch/mobile/node_modules/@expo/cli/src/start/server/middleware/CorsMiddleware.ts:26:11
    at call (/Users/theo/projects/monarch/mobile/node_modules/connect/index.js:239:7)
    at next (/Users/theo/projects/monarch/mobile/node_modules/connect/index.js:183:5)
    at suppressRemoteDebuggingErrorMiddleware (/Users/theo/projects/monarch/mobile/node_modules/@expo/cli/src/start/server/middleware/suppressErrorMiddleware.ts:16:3)
    at call (/Users/theo/projects/monarch/mobile/node_modules/connect/index.js:239:7)
    at Immediate.next [as _onImmediate] (/Users/theo/projects/monarch/mobile/node_modules/connect/index.js:183:5)
```

The built-in react devtools run fine (and doesn't emit that error) and it's also via this port as well, so it might not be an issue.

It doesn't prevent me from running the redux devtools plugin, though.

My setup follows the RTK example you have.

**Comment by matt-oakes** [comment] 2024-06-12 07:53
Hello. Thanks for reporting this.

Where exactly is this error being reported? Is this from the Expo CLI or in the browser console when the dev tools are open?

**Comment by theogravity** [comment] 2024-06-18 18:24
This is when I select the plugin from the CLI after hitting shift + M (in macOS)

<img width="663" alt="image" src="https://github.com/matt-oakes/redux-devtools-expo-dev-plugin/assets/855434/e77a8064-f69c-44eb-bc41-34d16fc8bd59">

![image](https://github.com/matt-oakes/redux-devtools-expo-dev-plugin/assets/855434/b2a6738f-9b4b-46ea-b5da-27ee215c2eb3)

**Comment by matt-oakes** [comment] 2024-06-23 09:50
When you say this:

> It doesn't prevent me from running the redux devtools plugin, though

Does this mean that you are able to use this devtools plugin even though you're getting this error? Does it stop you doing anything?

**Comment by theogravity** [comment] 2024-06-23 17:47
Works without problems

**Comment by matt-oakes** [comment] 2024-06-26 06:56
Ok. In that case I'm going to close this issue. If you're able to reproduce the issue and find out why it's happening then feel free to open a new issue with details about it and we can try to fix it.

Thanks again.

**Closed as completed by matt-oakes** 2024-06-26 06:56 UTC
Labels: bug, waiting for response

**Comment by theogravity** [comment] 2024-06-26 07:23
The issue does happen, it's reproducible on my machine, just don't know what causes it. It doesn't seem to interfere with my ability to use the plugin.

**Comment by matt-oakes** [comment] 2024-06-26 07:41
I know the issue is happening on your machine, but a proper reproduction would allow us to see the issue on other machines.

If you can figure out the root cause then feel free to open a new issue. A new issue is easier for me to find than a comment on a closed issue.
