### ISSUE TITLE
Type error on enhancer

### ISSUE THREAD

**Issue by Brandon-Perry** [matt-oakes/redux-devtools-expo-dev-plugin#17] opened 2024-11-21 04:35 UTC
I followed the instructions to add this and got this type error on the enhancer prop in configureStore. I can confirm the devtool works however, so this isn't a breaking issue. I'm using the latest version of expo. Let me know if there's any other info that's useful.

```
Type '(getDefaultEnhancers: GetDefaultEnhancers<import("/Users/me/client/node_modules/@reduxjs/toolkit/dist/index").Tuple<[import("node_modules/@reduxjs/toolkit/dist/index").ListenerMiddleware<unknown, import("/Users/...' is not assignable to type '(getDefaultEnhancers: GetDefaultEnhancers<import("/node_modules/@reduxjs/toolkit/dist/index").Tuple<[import("node_modules/@reduxjs/toolkit/dist/index").ListenerMiddleware<unknown, import(...'. Two different types with this name exist, but they are unrelated.
  Type 'Tuple<[StoreEnhancer<...>, StoreEnhancer]>' is not assignable to type 'Tuple<Enhancers>'.
    Type '[StoreEnhancer<...>, StoreEnhancer]' is not assignable to type 'Enhancers'.
      Type 'StoreEnhancer<...> | StoreEnhancer' is not assignable to type 'StoreEnhancer'.
        Type 'import("/node_modules/redux/index").StoreEnhancer' is not assignable to type 'import("node_modules/@reduxjs/toolkit/node_modules/redux/dist/redux").StoreEnhancer'.
          Types of parameters 'next' and 'next' are incompatible.
            Types of parameters 'reducer' and 'reducer' are incompatible.
              Type 'Reducer<S, A>' is not assignable to type 'Reducer<S, A, PreloadedState<S>>'.
                Types of parameters 'state' and 'state' are incompatible.
                  Type 'S | PreloadedState<S> | undefined' is not assignable to type 'S | undefined'.
                    Type 'PreloadedState<S>' is not assignable to type 'S | undefined'.
                      Type '(S extends CombinedState<infer S1> ? { [K in keyof S1]?: (S1[K] extends object ? PreloadedState<S1[K]> : S1[K]) | undefined; } : S) | { [K in keyof S]: S[K] extends string | ... 2 more ... | symbol ? S[K] : PreloadedState<...>; }' is not assignable to type 'S | undefined'.
                        Type 'S extends CombinedState<infer S1> ? { [K in keyof S1]?: (S1[K] extends object ? PreloadedState<S1[K]> : S1[K]) | undefined; } : S' is not assignable to type 'S | undefined'.
                          Type 'S | {}' is not assignable to type 'S | undefined'.
                            Type '{}' is not assignable to type 'S'.
                              'S' could be instantiated with an arbitrary type which could be unrelated to '{}'.ts(2719)
index.d.ts(570, 5): The expected type comes from property 'enhancers' which is declared here on type 'ConfigureStoreOptions<{ splash: SplashState; }, UnknownAction, Tuple<[ListenerMiddleware<unknown, ThunkDispatch<unknown, unknown, UnknownAction>, unknown>, ThunkMiddleware<...>]>, Tuple<...>, { ...; }>'
(property) ConfigureStoreOptions<{ splash: SplashState; }, UnknownAction, Tuple<[ThunkMiddleware<{ splash: SplashState; }, UnknownAction>]>, Tuple<...>, { ...; }>.enhancers?: ((getDefaultEnhancers: GetDefaultEnhancers<Tuple<[ThunkMiddleware<{
    splash: SplashState;
}, UnknownAction>]>>) => Tuple<...>) | undefined


```

**Comment by matt-oakes** [comment] 2024-11-22 13:43
Duplicate of #12

**Closed as not planned by matt-oakes** 2024-11-22 13:43 UTC
